windows_iso_path   = "winserver2025-final.iso"
cloudbase_msi_path = "input/CloudbaseInitSetup_x64.msi"
output_directory   = "output/"
admin_password     = "P@ssw0rd-Build!"
disk_size          = "40960"
